Fixes #19908: Strict mode of file_key_value_present_option does not introduce unwanted escpaing characters
Normation/ncf pull request #1307
Opened 2021-09-02 18:12 UTC by Fdall

https://issues.rudder.io/issues/19908

2021-09-02 18:44 UTC, ncharles commented on tree/30_generic_methods/file_key_value_present_option.cf
> +      "full_class_prefix" string => canonify("file_key_value_present_option_${report_param}");
You cannot change this: the advertised class_prefix is file_key_value_present_

2021-09-02 18:47 UTC, ncharles requested changes
you shouldn't change the class_prefix

2021-09-02 19:07 UTC, Fdall commented
PR updated with a new commit

2021-09-02 19:10 UTC, Fdall commented on tree/30_generic_methods/file_key_value_present_option.cf
> +      "updated_full_class_prefix" string => canonify("file_key_value_present_optin_${report_param}");
```suggestion
      "updated_full_class_prefix" string => canonify("file_key_value_present_option_${report_param}");
```

2021-09-02 19:11 UTC, Fdall commented on tree/30_generic_methods/file_key_value_present_option.cf
> +      "updated_class_prefix"      string => string_head("${full_class_prefix}", "1000");
```suggestion
      "updated_class_prefix"      string => string_head("${updated_full_class_prefix}", "1000");
```

2021-09-02 19:28 UTC, ncharles approved these changes

2021-09-14 12:46 UTC, Fdall commented
PR rebased

2021-09-17 16:14 UTC, Fdall commented
PR rebased

2021-09-17 16:38 UTC, Fdall commented
PR updated with a new commit

2021-09-20 07:51 UTC, Fdall commented
PR updated with a new commit

2021-09-20 08:10 UTC, Fdall commented
PR updated with a new commit

2021-09-20 09:23 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/ncf/pull/1307`
-- Your faithful QA
Kant merge: "To be is to do."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/44534/console)

2021-09-20 09:26 UTC, Fdall commented
OK, squash merging this PR

2021-09-20 09:26 UTC, merged

2021-09-20 09:32 UTC, Fdall commented
OK, merging this PR