Fixes #21266: Cleanup ncf repo
Normation/ncf pull request #1356
Opened 2022-06-15 15:53 UTC by amousset

https://issues.rudder.io/issues/21266

2022-06-15 15:55 UTC, amousset commented
PR updated with a new commit

2022-06-15 21:14 UTC, ncharles commented on README.md
> +  - __50_techniques__: This directory contains Techniques, which uses generic_methods to achieve system configurations you need. They may be generic ("Configure OpenSSH server") or specific ("Install
we should remove it, nothing ever use it

2022-06-15 21:15 UTC, ncharles requested changes
You should drop the mention about 50_techniques in the main README.md

2022-06-15 21:30 UTC, amousset commented on tree/10_ncf_internals/initialization.cf
> -      "${configuration.debug} File read from 10_ncf_internals: ${inputs.ncf_internals_files}";
these are not used in promises.st anymore

2022-06-22 13:52 UTC, ncharles approved these changes

2022-06-22 17:20 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/ncf/pull/1356`
-- Your faithful QA
Kant merge: "Morality is not the doctrine of how we may make ourselves happy, but how we may make ourselves worthy of happiness."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/56049/console)

2022-06-22 17:20 UTC, amousset commented
OK, squash merging this PR

2022-06-22 17:36 UTC, merged